nomagic probe
=============

The nomagic probe is a firmware for the https://www.raspberrypi.com/products/raspberry-pi-pico/[RaspberryPi Pico board] that provides a gdbserver interface for debugging other boards.
That is the functionality of the https://github.com/raspberrypi/picoprobe[picoprobe] and https://openocd.org/[OpenOCD] combined. It is therefore similar to the https://black-magic.org/[Black Magic Firmware].

It does not use external libraries. Therefore all code is in this project, no dependencies!

No dynamic memory allocation, no malloc!

== Building

This project contains the necessary project files to be opened by the https://embeetle.com/[Embeetle IDE].

This project also has https://www.eclipse.org/[Eclipse] project files.

The firmware can also be build using make. To build using make you first need to change into the build directory. The build directory can be any folder you like. This allows also to have dmore than one build directory.
In the build directory you can make normally, but need to provide the path to the makefile.

----
cd build/

# to build:
make -f ../config/makefile
# to flash
make -f ../config/makefile flash
# to clean
make -f ../config/makefile clean
----

For this to work you (obviously) need to have make installed.
Depending on the target you are building for you might need to have additionaltools installed:

- To build for ARM Cortex-M Targets you need https://launchpad.net/gcc-arm-embedded[GCC ARM Embedded]
- for automatic generated documentation you need http://www.stack.nl/~dimitri/doxygen/[Doxygen]

== Pinout

=== pico
The pico has 20 pins (1..40) Numbered counter clock wise starting at the USB connector.

Pin 21: (GPIO 16) Debug Uart TX (UART0)

Pin 22: (GPIO 17) Debug Uart RX (UART0)



== License

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, see <http://www.gnu.org/licenses/>
