= GDB Server

== Packets

all packets: "$packet-data#checksum"

notification packets: "% data # checksum" ( Example : %Stop:...)

empty response is "$#00"

== commands

=== Thread id

[cols="1,1"]
|===
| id
| Meaning

| -1
| all threads

| 0
| any thread

| 1
| first thread

| p1.-1
| all threads in process 1

|===

== Links

https://www.embecosm.com/appnotes/ean4/embecosm-howto-rsp-server-ean4-issue-2.html

https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_129.html

https://www.zeuthen.desy.de/dv/documentation/unixguide/infohtml/gdb/General-Query-Packets.html

https://ftp.gnu.org/old-gnu/Manuals/gdb/html_chapter/gdb_15.html

https://sourceware.org/gdb/onlinedocs/gdb/Remote-Protocol.html#Remote-Protocol[gdbserver protocol]

https://black-magic.org/[Black Magic Firmware]

== Dictionary

There are some GDB specific words used that only make sense in the GDB contet. These words are defined here.

[cols="1,1"]
|===
| Word
| Meaning

| stub
| the JTAG/SWD probe

| process
| processes can have one or more threads. Each proces has a seperate memory and can not access the memory of another process.

| thread
| A code execution path. Threads can access the memory of other threads in the same process. (Embeedde context: in bare metal we have one thread per CPU core. If the firmware uses an OS then we can be "aware" of the threads of the OS.

|===
