/*
  automatically created from data available on https://chipselect.org/
*/
#ifndef HW_IO_QSPI_H
#define HW_IO_QSPI_H
/** Interrupt : IO_IRQ_QSPI (Vector: 14)  */
/** Memory Block starting at 0x40018000 + 0x0 is 0x1000 bytes in size. It is used for registers. Protection: n */

#include <stdint.h>


#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC_OFFSET     26u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQTOPROC_MASK       0x4000000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQFROMPAD_OFFSET    24u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_IRQFROMPAD_MASK      0x1000000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INTOPERI_OFFSET      19u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INTOPERI_MASK        0x80000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD_OFFSET     17u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_INFROMPAD_MASK       0x20000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD_OFFSET       13u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OETOPAD_MASK         0x2000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OEFROMPERI_OFFSET    12u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OEFROMPERI_MASK      0x1000u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD_OFFSET      9u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTTOPAD_MASK        0x200u

#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTFROMPERI_OFFSET   8u
#define IO_QSPI_GPIO_QSPI_SCLK_STATUS_OUTFROMPERI_MASK     0x100u

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_OFFSET         28u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_MASK           0x30000000u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_NORMAL         0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_INVERT         1u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_LOW            2u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_IRQOVER_HIGH           3u

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_OFFSET          16u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_MASK            0x30000u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_INOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_OFFSET          12u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_MASK            0x3000u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_DISABLE         2u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OEOVER_ENABLE          3u

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_OFFSET         8u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_MASK           0x300u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_NORMAL         0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_INVERT         1u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_LOW            2u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_OUTOVER_HIGH           3u

#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_OFFSET         0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_MASK           0x1fu
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_XIP_SCLK       0u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_SIO_30         5u
#define IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_NULL           0x1fu

#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC_OFFSET       26u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQTOPROC_MASK         0x4000000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQFROMPAD_OFFSET      24u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_IRQFROMPAD_MASK        0x1000000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_INTOPERI_OFFSET        19u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INTOPERI_MASK          0x80000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD_OFFSET       17u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_INFROMPAD_MASK         0x20000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD_OFFSET         13u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OETOPAD_MASK           0x2000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_OEFROMPERI_OFFSET      12u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OEFROMPERI_MASK        0x1000u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD_OFFSET        9u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTTOPAD_MASK          0x200u

#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTFROMPERI_OFFSET     8u
#define IO_QSPI_GPIO_QSPI_SS_STATUS_OUTFROMPERI_MASK       0x100u

#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_OFFSET           28u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_MASK             0x30000000u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_IRQOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_OFFSET            16u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_MASK              0x30000u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_NORMAL            0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_INVERT            1u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_LOW               2u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_INOVER_HIGH              3u

#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_OFFSET            12u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_MASK              0x3000u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_NORMAL            0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_INVERT            1u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_DISABLE           2u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OEOVER_ENABLE            3u

#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_OFFSET           8u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_MASK             0x300u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_OUTOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_OFFSET           0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_MASK             0x1fu
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_XIP_SS_N         0u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_SIO_31           5u
#define IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_NULL             0x1fu

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC_OFFSET      26u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQTOPROC_MASK        0x4000000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQFROMPAD_OFFSET     24u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_IRQFROMPAD_MASK       0x1000000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INTOPERI_OFFSET       19u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INTOPERI_MASK         0x80000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD_OFFSET      17u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_INFROMPAD_MASK        0x20000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD_OFFSET        13u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OETOPAD_MASK          0x2000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OEFROMPERI_OFFSET     12u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OEFROMPERI_MASK       0x1000u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD_OFFSET       9u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTTOPAD_MASK         0x200u

#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTFROMPERI_OFFSET    8u
#define IO_QSPI_GPIO_QSPI_SD0_STATUS_OUTFROMPERI_MASK      0x100u

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_OFFSET          28u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_MASK            0x30000000u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_IRQOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_OFFSET           16u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_MASK             0x30000u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_INOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_OFFSET           12u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_MASK             0x3000u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_DISABLE          2u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OEOVER_ENABLE           3u

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_OFFSET          8u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_MASK            0x300u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_OUTOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_OFFSET          0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_MASK            0x1fu
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_XIP_SD0         0u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_SIO_32          5u
#define IO_QSPI_GPIO_QSPI_SD0_CTRL_FUNCSEL_NULL            0x1fu

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC_OFFSET      26u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQTOPROC_MASK        0x4000000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQFROMPAD_OFFSET     24u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_IRQFROMPAD_MASK       0x1000000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INTOPERI_OFFSET       19u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INTOPERI_MASK         0x80000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD_OFFSET      17u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_INFROMPAD_MASK        0x20000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD_OFFSET        13u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OETOPAD_MASK          0x2000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OEFROMPERI_OFFSET     12u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OEFROMPERI_MASK       0x1000u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD_OFFSET       9u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTTOPAD_MASK         0x200u

#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTFROMPERI_OFFSET    8u
#define IO_QSPI_GPIO_QSPI_SD1_STATUS_OUTFROMPERI_MASK      0x100u

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_OFFSET          28u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_MASK            0x30000000u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_IRQOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_OFFSET           16u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_MASK             0x30000u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_INOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_OFFSET           12u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_MASK             0x3000u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_DISABLE          2u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OEOVER_ENABLE           3u

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_OFFSET          8u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_MASK            0x300u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_OUTOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_OFFSET          0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_MASK            0x1fu
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_XIP_SD1         0u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_SIO_33          5u
#define IO_QSPI_GPIO_QSPI_SD1_CTRL_FUNCSEL_NULL            0x1fu

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC_OFFSET      26u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQTOPROC_MASK        0x4000000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQFROMPAD_OFFSET     24u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_IRQFROMPAD_MASK       0x1000000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INTOPERI_OFFSET       19u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INTOPERI_MASK         0x80000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD_OFFSET      17u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_INFROMPAD_MASK        0x20000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD_OFFSET        13u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OETOPAD_MASK          0x2000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OEFROMPERI_OFFSET     12u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OEFROMPERI_MASK       0x1000u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD_OFFSET       9u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTTOPAD_MASK         0x200u

#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTFROMPERI_OFFSET    8u
#define IO_QSPI_GPIO_QSPI_SD2_STATUS_OUTFROMPERI_MASK      0x100u

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_OFFSET          28u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_MASK            0x30000000u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_IRQOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_OFFSET           16u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_MASK             0x30000u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_INOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_OFFSET           12u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_MASK             0x3000u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_DISABLE          2u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OEOVER_ENABLE           3u

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_OFFSET          8u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_MASK            0x300u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_OUTOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_OFFSET          0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_MASK            0x1fu
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_XIP_SD2         0u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_SIO_34          5u
#define IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_NULL            0x1fu

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC_OFFSET      26u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQTOPROC_MASK        0x4000000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQFROMPAD_OFFSET     24u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_IRQFROMPAD_MASK       0x1000000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INTOPERI_OFFSET       19u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INTOPERI_MASK         0x80000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD_OFFSET      17u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_INFROMPAD_MASK        0x20000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD_OFFSET        13u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OETOPAD_MASK          0x2000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OEFROMPERI_OFFSET     12u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OEFROMPERI_MASK       0x1000u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD_OFFSET       9u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTTOPAD_MASK         0x200u

#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTFROMPERI_OFFSET    8u
#define IO_QSPI_GPIO_QSPI_SD3_STATUS_OUTFROMPERI_MASK      0x100u

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_OFFSET          28u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_MASK            0x30000000u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_IRQOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_OFFSET           16u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_MASK             0x30000u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_LOW              2u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_INOVER_HIGH             3u

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_OFFSET           12u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_MASK             0x3000u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_NORMAL           0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_INVERT           1u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_DISABLE          2u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OEOVER_ENABLE           3u

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_OFFSET          8u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_MASK            0x300u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_NORMAL          0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_INVERT          1u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_LOW             2u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_OUTOVER_HIGH            3u

#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_OFFSET          0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_MASK            0x1fu
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_XIP_SD3         0u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_SIO_35          5u
#define IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_NULL            0x1fu

#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET        23u
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_MASK          0x800000u

#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_OFFSET         22u
#define IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_MASK           0x400000u

#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET       21u
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_MASK         0x200000u

#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET        20u
#define IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_MASK          0x100000u

#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET        19u
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_MASK          0x80000u

#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_OFFSET         18u
#define IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_MASK           0x40000u

#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET       17u
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_MASK         0x20000u

#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET        16u
#define IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_MASK          0x10000u

#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET        15u
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_MASK          0x8000u

#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_OFFSET         14u
#define IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_MASK           0x4000u

#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET       13u
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_MASK         0x2000u

#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET        12u
#define IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_MASK          0x1000u

#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET        11u
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_MASK          0x800u

#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_OFFSET         10u
#define IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_MASK           0x400u

#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET       9u
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_MASK         0x200u

#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET        8u
#define IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_MASK          0x100u

#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_OFFSET         7u
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_MASK           0x80u

#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_OFFSET          6u
#define IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_MASK            0x40u

#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET        5u
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_MASK          0x20u

#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_OFFSET         4u
#define IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_MASK           0x10u

#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET       3u
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_MASK         8u

#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET        2u
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_MASK          4u

#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET      1u
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK        2u

#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET       0u
#define IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_MASK         1u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC0_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC0_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC0_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC1_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC1_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET  23u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK    0x800000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK     0x400000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET  20u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK    0x100000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET  19u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK    0x80000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK     0x40000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET  16u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK    0x10000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET  15u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK    0x8000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK     0x4000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET  12u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK    0x1000u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET  11u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK    0x800u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK     0x400u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET  8u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK    0x100u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK     0x80u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW_OFFSET    6u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK      0x40u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET  5u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK    0x20u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK     0x10u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET  2u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK    4u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK  2u

#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_PROC1_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET   23u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_MASK   0x800000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_MASK   0x400000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET   20u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_MASK   0x100000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET   19u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_MASK   0x80000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_MASK   0x40000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET   16u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_MASK   0x10000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET   15u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_MASK   0x8000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_MASK   0x4000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET   12u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_MASK   0x1000u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET   11u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_MASK   0x800u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_MASK   0x400u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET   8u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_MASK   0x100u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_MASK   0x80u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_OFFSET   6u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_MASK   0x40u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET   5u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_MASK   0x20u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_MASK   0x10u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET   2u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_MASK   4u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK   2u

#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET   23u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_MASK   0x800000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_MASK   0x400000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET   20u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_MASK   0x100000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET   19u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_MASK   0x80000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_MASK   0x40000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET   16u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_MASK   0x10000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET   15u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_MASK   0x8000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_MASK   0x4000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET   12u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_MASK   0x1000u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET   11u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_MASK   0x800u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_MASK   0x400u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET   8u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_MASK   0x100u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_MASK   0x80u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_OFFSET   6u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_MASK   0x40u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET   5u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_MASK   0x20u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_MASK   0x10u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET   2u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_MASK   4u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK   2u

#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_OFFSET   23u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_MASK   0x800000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_OFFSET   22u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_MASK   0x400000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_OFFSET   21u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_MASK   0x200000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_OFFSET   20u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_MASK   0x100000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_OFFSET   19u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_MASK   0x80000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_OFFSET   18u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_MASK   0x40000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_OFFSET   17u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_MASK   0x20000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_OFFSET   16u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_MASK   0x10000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_OFFSET   15u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_MASK   0x8000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_OFFSET   14u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_MASK   0x4000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_OFFSET   13u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_MASK   0x2000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_OFFSET   12u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_MASK   0x1000u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_OFFSET   11u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_MASK   0x800u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_OFFSET   10u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_MASK   0x400u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_OFFSET   9u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_MASK   0x200u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_OFFSET   8u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_MASK   0x100u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_OFFSET   7u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_MASK   0x80u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_OFFSET   6u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_MASK   0x40u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_OFFSET   5u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_MASK   0x20u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_OFFSET   4u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_MASK   0x10u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_OFFSET   3u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_MASK   8u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_OFFSET   2u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_MASK   4u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_OFFSET   1u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_MASK   2u

#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_OFFSET   0u
#define IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_MASK   1u


typedef struct
{

/** GPIO_QSPI_SCLK_STATUS (offset: 0x0)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SCLK_STATUS;

/** GPIO_QSPI_SCLK_CTRL (offset: 0x4)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_sclk
  Value: 5 - sio_30
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SCLK_CTRL;

/** GPIO_QSPI_SS_STATUS (offset: 0x8)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SS_STATUS;

/** GPIO_QSPI_SS_CTRL (offset: 0xc)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_ss_n
  Value: 5 - sio_31
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SS_CTRL;

/** GPIO_QSPI_SD0_STATUS (offset: 0x10)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SD0_STATUS;

/** GPIO_QSPI_SD0_CTRL (offset: 0x14)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_sd0
  Value: 5 - sio_32
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SD0_CTRL;

/** GPIO_QSPI_SD1_STATUS (offset: 0x18)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SD1_STATUS;

/** GPIO_QSPI_SD1_CTRL (offset: 0x1c)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_sd1
  Value: 5 - sio_33
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SD1_CTRL;

/** GPIO_QSPI_SD2_STATUS (offset: 0x20)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SD2_STATUS;

/** GPIO_QSPI_SD2_CTRL (offset: 0x24)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_sd2
  Value: 5 - sio_34
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SD2_CTRL;

/** GPIO_QSPI_SD3_STATUS (offset: 0x28)
  GPIO status
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: IRQTOPROC
  offset: 26, size: 1, access: read-only
  interrupt to processors, after override is applied
  Field: IRQFROMPAD
  offset: 24, size: 1, access: read-only
  interrupt from pad before override is applied
  Field: INTOPERI
  offset: 19, size: 1, access: read-only
  input signal to peripheral, after override is applied
  Field: INFROMPAD
  offset: 17, size: 1, access: read-only
  input signal from pad, before override is applied
  Field: OETOPAD
  offset: 13, size: 1, access: read-only
  output enable to pad after register override is applied
  Field: OEFROMPERI
  offset: 12, size: 1, access: read-only
  output enable from selected peripheral, before register override is applied
  Field: OUTTOPAD
  offset: 9, size: 1, access: read-only
  output signal to pad after register override is applied
  Field: OUTFROMPERI
  offset: 8, size: 1, access: read-only
  output signal from selected peripheral, before register override is applied
*/
volatile uint32_t GPIO_QSPI_SD3_STATUS;

/** GPIO_QSPI_SD3_CTRL (offset: 0x2c)
  GPIO control including function select and overrides.
  access : read-write
  reset value : 0x1F
  reset mask : 0x0
  Field: IRQOVER
  offset: 28, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the interrupt
  Value: 1 - INVERT : invert the interrupt
  Value: 2 - LOW : drive interrupt low
  Value: 3 - HIGH : drive interrupt high
  Field: INOVER
  offset: 16, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : don&apos;t invert the peri input
  Value: 1 - INVERT : invert the peri input
  Value: 2 - LOW : drive peri input low
  Value: 3 - HIGH : drive peri input high
  Field: OEOVER
  offset: 12, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output enable from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output enable from inverse of peripheral signal selected by funcsel
  Value: 2 - DISABLE : disable output
  Value: 3 - ENABLE : enable output
  Field: OUTOVER
  offset: 8, size: 2, access: read-write
  Enum:
  Value: 0 - NORMAL : drive output from peripheral signal selected by funcsel
  Value: 1 - INVERT : drive output from inverse of peripheral signal selected by funcsel
  Value: 2 - LOW : drive output low
  Value: 3 - HIGH : drive output high
  Field: FUNCSEL
  offset: 0, size: 5, access: read-write
  0-31 -&gt; selects pin function according to the gpio table

 31 == NULL
  Enum:
  Value: 0 - xip_sd3
  Value: 5 - sio_35
  Value: 0x1f - null
*/
volatile uint32_t GPIO_QSPI_SD3_CTRL;

/** INTR (offset: 0x30)
  Raw Interrupts
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-only
*/
volatile uint32_t INTR;

/** PROC0_INTE (offset: 0x34)
  Interrupt Enable for proc0
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t PROC0_INTE;

/** PROC0_INTF (offset: 0x38)
  Interrupt Force for proc0
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t PROC0_INTF;

/** PROC0_INTS (offset: 0x3c)
  Interrupt status after masking &amp; forcing for proc0
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-only
*/
volatile uint32_t PROC0_INTS;

/** PROC1_INTE (offset: 0x40)
  Interrupt Enable for proc1
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t PROC1_INTE;

/** PROC1_INTF (offset: 0x44)
  Interrupt Force for proc1
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t PROC1_INTF;

/** PROC1_INTS (offset: 0x48)
  Interrupt status after masking &amp; forcing for proc1
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-only
*/
volatile uint32_t PROC1_INTS;

/** DORMANT_WAKE_INTE (offset: 0x4c)
  Interrupt Enable for dormant_wake
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t DORMANT_WAKE_INTE;

/** DORMANT_WAKE_INTF (offset: 0x50)
  Interrupt Force for dormant_wake
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-write
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-write
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-write
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-write
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-write
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-write
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-write
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-write
*/
volatile uint32_t DORMANT_WAKE_INTF;

/** DORMANT_WAKE_INTS (offset: 0x54)
  Interrupt status after masking &amp; forcing for dormant_wake
  access : read-write
  reset value : 0x0
  reset mask : 0x0
  Field: GPIO_QSPI_SD3_EDGE_HIGH
  offset: 23, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_EDGE_LOW
  offset: 22, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_HIGH
  offset: 21, size: 1, access: read-only
  Field: GPIO_QSPI_SD3_LEVEL_LOW
  offset: 20, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_HIGH
  offset: 19, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_EDGE_LOW
  offset: 18, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_HIGH
  offset: 17, size: 1, access: read-only
  Field: GPIO_QSPI_SD2_LEVEL_LOW
  offset: 16, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_HIGH
  offset: 15, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_EDGE_LOW
  offset: 14, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_HIGH
  offset: 13, size: 1, access: read-only
  Field: GPIO_QSPI_SD1_LEVEL_LOW
  offset: 12, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_HIGH
  offset: 11, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_EDGE_LOW
  offset: 10, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_HIGH
  offset: 9, size: 1, access: read-only
  Field: GPIO_QSPI_SD0_LEVEL_LOW
  offset: 8, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_HIGH
  offset: 7, size: 1, access: read-only
  Field: GPIO_QSPI_SS_EDGE_LOW
  offset: 6, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_HIGH
  offset: 5, size: 1, access: read-only
  Field: GPIO_QSPI_SS_LEVEL_LOW
  offset: 4, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_HIGH
  offset: 3, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_EDGE_LOW
  offset: 2, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_HIGH
  offset: 1, size: 1, access: read-only
  Field: GPIO_QSPI_SCLK_LEVEL_LOW
  offset: 0, size: 1, access: read-only
*/
volatile uint32_t DORMANT_WAKE_INTS;
} IO_QSPI_type;

#define IO_QSPI ((IO_QSPI_type *) 0x40018000)

#endif // HW_IO_QSPI_H
